PROJECT = erlang_benchmarks
PROJECT_DESCRIPTION = Erlang Benchmark implementations for the Kompics Benchmark Suite
PROJECT_VERSION = 0.1.0

# ERLANG_OTP = OTP-22.0.2

SP = 4

DOC_DEPS = edown
EDOC_OPTS = {doclet, edown_doclet}

DEPS = grpc grpc_client

include erlang.mk
